nama = input ("Nama : ")
nim = input ("Nim : ")
paralel = input ("kelas Paralel :")
ttl = input ("Tempat Tanggal Lahir : ")
alamat = input ("Alamat : ")
hobby = input ("Hobby : ")
hp = input ("Nomor HP : ")

print ("=============Output=========================")
print ("Nama                 : ", nama)
print ("NIM                  : ", nim)
print ("Kelas Paralel        : ", paralel )
print ("Tempat/tanggal lahir : ", ttl)
print ("Alamat               : ", alamat)
print ("Hobby                : ", hobby)
print ("No.Hp                : ", hp )